### ISSUE TITLE
How to achieve arbitrary scale super resolution, such as generating a set of images 3.4 times enlarged?

### ISSUE THREAD

**Issue by Nertiii** [pbehjatii/OverNet#3]
How to achieve arbitrary scale super resolution, such as generating a set of images 3.4 times enlarged?

**Comment by pbehjatii** [comment]
We have used interpolation techniques to generate arbitrary scale factors. For example if you want to generate scale 3.4:

import torch.nn.functional as F
scale = 3.4
result = F.interpolate(out, (int(x.size(-2) * scale), int(x.size(-1) * scale)) , mode = 'bicubic', align_corners = False)

in which out is the output of your network, x is the input.
